/**
 * POST /api/verify
 * Runs full verification (test cases + security + benchmark) and posts results to Linear
 */

import { NextRequest, NextResponse } from 'next/server';
import { getIssueByIdentifier, addComment } from '@/lib/linear';
import { buildEnrichmentPrompt, type TicketEnrichment } from '@/lib/ai';
import { scanEndpoint } from '@/lib/scanner';
import { benchmarkEndpoint } from '@/lib/scanner';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { identifier, postComment = true } = body;

    if (!identifier) {
      return NextResponse.json({ error: 'identifier required' }, { status: 400 });
    }

    const issue = await getIssueByIdentifier(identifier);
    const stagingApi = process.env.STAGING_API_URL || 'https://dev.bep.creator.fun';
    const stagingUrl = process.env.STAGING_URL || 'https://dev.creator.fun';

    // 1. Run security scan on default endpoints
    const endpoints = ['/api/token', '/api/watchlist', '/api/user', '/api/chat', '/api/trade', '/api/holdings', '/api/leaderboard'];
    const securityResults = await Promise.all(
      endpoints.map(ep => scanEndpoint(`${stagingApi}${ep}`))
    );

    const secSummary = {
      total: securityResults.length,
      passed: securityResults.filter(r => r.overallStatus === 'pass').length,
      warnings: securityResults.filter(r => r.overallStatus === 'warn').length,
      failed: securityResults.filter(r => r.overallStatus === 'fail').length,
    };

    // 2. Run performance benchmark
    const ourPerf = await benchmarkEndpoint(stagingUrl);
    const axiomPerf = await benchmarkEndpoint('https://axiom.trade');
    const pumpPerf = await benchmarkEndpoint('https://pump.fun');

    // 3. Format and post to Linear
    if (postComment) {
      let comment = `## 🛡️ QA Shield — Verification Report\n\n`;
      comment += `**Ticket:** ${issue.identifier} — ${issue.title}\n`;
      comment += `**Verified at:** ${new Date().toISOString()}\n\n`;

      // Security Results
      comment += `### 🔒 Security Scan\n\n`;
      comment += `| Status | Count |\n|--------|-------|\n`;
      comment += `| ✅ Passed | ${secSummary.passed} |\n`;
      comment += `| ⚠️ Warnings | ${secSummary.warnings} |\n`;
      comment += `| ❌ Failed | ${secSummary.failed} |\n\n`;

      for (const r of securityResults) {
        const icon = r.overallStatus === 'pass' ? '✅' : r.overallStatus === 'fail' ? '❌' : '⚠️';
        const ep = r.endpoint.split('/api')[1] || r.endpoint;
        comment += `${icon} **${ep}**\n`;
        for (const c of r.checks) {
          if (c.status !== 'pass') {
            comment += `  - [${c.type.toUpperCase()}] ${c.details}\n`;
          }
        }
      }

      // Performance Benchmark
      comment += `\n### ⚡ Performance Benchmark\n\n`;
      comment += `| Platform | Response Time | TTFB | Status |\n`;
      comment += `|----------|--------------|------|--------|\n`;
      comment += `| **creator.fun** | ${ourPerf.responseTime}ms | ${ourPerf.ttfb}ms | ${ourPerf.statusCode} |\n`;
      comment += `| axiom.trade | ${axiomPerf.responseTime}ms | ${axiomPerf.ttfb}ms | ${axiomPerf.statusCode} |\n`;
      comment += `| pump.fun | ${pumpPerf.responseTime}ms | ${pumpPerf.ttfb}ms | ${pumpPerf.statusCode} |\n\n`;

      // Verdict
      const faster = ourPerf.responseTime < axiomPerf.responseTime && ourPerf.responseTime < pumpPerf.responseTime;
      const slower = ourPerf.responseTime > axiomPerf.responseTime && ourPerf.responseTime > pumpPerf.responseTime;
      if (faster) {
        comment += `✅ **We're faster than both competitors!**\n`;
      } else if (slower) {
        comment += `⚠️ **We're slower than competitors — needs optimization**\n`;
      } else {
        comment += `🟡 **Mixed results — competitive on some metrics**\n`;
      }

      comment += `\n---\n_Generated by QA Shield 🛡️ — automated verification_`;

      await addComment(issue.id, comment);
    }

    return NextResponse.json({
      success: true,
      identifier: issue.identifier,
      security: { summary: secSummary, results: securityResults },
      benchmark: {
        ours: ourPerf,
        competitors: [
          { name: 'axiom.trade', result: axiomPerf },
          { name: 'pump.fun', result: pumpPerf },
        ],
      },
      commentPosted: postComment,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
