/**
 * commit-runner.ts
 * Executes the targeted checks generated by commit-analyzer.ts.
 * Runs: browser DOM checks, API response checks, perf benchmarks, security scans.
 * Posts a comprehensive report to Linear as a comment.
 */

import { analyzeCommit, formatCommitAnalysisComment, type CommitAnalysis, type APICheck } from './commit-analyzer';
import { addComment, getIssueByIdentifier, updateIssueState, WORKFLOW_STATES } from './linear';
import { scanEndpoint } from './scanner';
import type { GitHubFile } from './github';

const BROWSER_WORKER = process.env.BROWSER_WORKER_URL || 'http://127.0.0.1:3099';
const STAGING_API = process.env.STAGING_API_URL || 'https://dev.bep.creator.fun';

// ── Competitor reference latencies (in ms) for perf comparison ──
const COMPETITOR_BASELINES: Array<{ name: string; avgMs: number }> = [
  { name: 'pump.fun', avgMs: 25 },
  { name: 'axiom.trade', avgMs: 45 },
  { name: 'photon.trade', avgMs: 60 },
];

// ============ DOM checker via browser worker ============

async function runDOMChecks(pagePath: string, checks: any[]): Promise<{
  path: string;
  passed: number;
  failed: number;
  checks: Array<{ description: string; passed: boolean; error?: string }>;
}> {
  const results: Array<{ description: string; passed: boolean; error?: string }> = [];

  try {
    // Browser worker expects `path` field (not `url`)
    // path can be full URL or relative path — worker prepends STAGING_URL if relative
    const res = await fetch(`${BROWSER_WORKER}/dom`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ path: pagePath, checks }),
      signal: AbortSignal.timeout(30000),
    });

    if (!res.ok) {
      return { path: pagePath, passed: 0, failed: checks.length, checks: checks.map(c => ({ description: c.description, passed: false, error: `Browser worker HTTP ${res.status}` })) };
    }

    const data = await res.json();
    const checkResults = data.results || [];

    for (let i = 0; i < checks.length; i++) {
      const r = checkResults[i];
      if (!r) { results.push({ description: checks[i].description, passed: false, error: 'No result returned' }); continue; }
      results.push({ description: checks[i].description, passed: r.passed ?? false, error: r.error });
    }
  } catch (err: any) {
    return { path: pagePath, passed: 0, failed: checks.length, checks: checks.map(c => ({ description: c.description, passed: false, error: err.message })) };
  }

  const passed = results.filter(r => r.passed).length;
  const failed = results.filter(r => !r.passed).length;
  return { path: pagePath, passed, failed, checks: results };
}

// ============ API checker ============

async function runAPICheck(check: APICheck): Promise<{
  endpoint: string;
  status: number;
  ok: boolean;
  issues: string[];
}> {
  const issues: string[] = [];
  try {
    const res = await fetch(check.endpoint, {
      method: check.method,
      headers: { 'Content-Type': 'application/json' },
      body: check.method === 'POST' ? JSON.stringify(check.body) : undefined,
      signal: AbortSignal.timeout(15000),
    });

    if (res.status !== check.expectedStatus) {
      issues.push(`Expected HTTP ${check.expectedStatus}, got ${res.status}`);
      return { endpoint: check.endpoint, status: res.status, ok: false, issues };
    }

    const data = await res.json().catch(() => ({}));

    for (const c of check.checks) {
      const val = getNestedValue(data, c.field);
      let passed = false;
      switch (c.type) {
        case 'exists': passed = val !== undefined && val !== null; break;
        case 'notNull': passed = val !== null && val !== undefined; break;
        case 'isArray': passed = Array.isArray(val); break;
        case 'isNumber': passed = typeof val === 'number' && !isNaN(val); break;
        case 'isString': passed = typeof val === 'string'; break;
        case 'isPositive': passed = typeof val === 'number' && val > 0; break;
        case 'equals': passed = val === c.value; break;
      }
      if (!passed) issues.push(`${c.description}: field "${c.field}" check "${c.type}" failed (got: ${JSON.stringify(val)?.slice(0, 50)})`);
    }

    return { endpoint: check.endpoint, status: res.status, ok: issues.length === 0, issues };
  } catch (err: any) {
    return { endpoint: check.endpoint, status: 0, ok: false, issues: [`Request failed: ${err.message}`] };
  }
}

function getNestedValue(obj: any, path: string): any {
  const parts = path.split('.');
  let val = obj;
  for (const p of parts) {
    if (val === null || val === undefined) return undefined;
    if (p === '0' && Array.isArray(val)) { val = val[0]; continue; }
    val = val[p];
  }
  return val;
}

// ============ Performance spot-check ============

async function runPerfCheck(endpoint: string): Promise<{
  endpoint: string;
  ourMs: number;
  fastestCompMs?: number;
  fastestCompName?: string;
  deltaPct?: number;
}> {
  const samples: number[] = [];
  for (let i = 0; i < 3; i++) {
    const t = Date.now();
    try {
      await fetch(endpoint, { signal: AbortSignal.timeout(10000) });
    } catch { /* ok */ }
    samples.push(Date.now() - t);
    if (i < 2) await new Promise(r => setTimeout(r, 500));
  }
  const ourMs = Math.round(samples.reduce((a, b) => a + b, 0) / samples.length);

  const fastest = COMPETITOR_BASELINES.sort((a, b) => a.avgMs - b.avgMs)[0];
  const deltaPct = fastest ? Math.round(((ourMs - fastest.avgMs) / fastest.avgMs) * 100) : undefined;

  return { endpoint, ourMs, fastestCompMs: fastest?.avgMs, fastestCompName: fastest?.name, deltaPct };
}

// ============ Security spot-check (1 sample per endpoint) ============

async function runSecurityCheck(endpoint: string): Promise<{ endpoint: string; issues: string[] }> {
  const issues: string[] = [];
  try {
    const res = await fetch(endpoint, {
      headers: { 'Origin': 'https://evil-site.example.com' },
      signal: AbortSignal.timeout(10000),
    });
    const acao = res.headers.get('access-control-allow-origin');
    if (acao === '*' || acao === 'https://evil-site.example.com') {
      issues.push(`CORS: allows Origin "evil-site.example.com" (ACAO: ${acao})`);
    }
    const hsts = res.headers.get('strict-transport-security');
    if (!hsts) issues.push('Missing HSTS header');
    const xcto = res.headers.get('x-content-type-options');
    if (!xcto) issues.push('Missing X-Content-Type-Options header');
  } catch (err: any) {
    // network errors don't count as security issues
  }
  return { endpoint, issues };
}

// ============ AI Task Queue (Chief QA proxy) ============

const QA_SHIELD_BASE = `http://localhost:${process.env.PORT || 3000}`;

interface AITestCase {
  area: string;           // e.g. "Trading UI", "Token Detail"
  description: string;    // what the test checks
  type: 'dom' | 'api';
  path?: string;          // for DOM: page path
  selector?: string;      // for DOM: CSS selector
  action?: string;        // for DOM: exists | visible | text-contains | not-exists
  expectedText?: string;  // for dom text-contains
  endpoint?: string;      // for API
  expectedStatus?: number;
  expectField?: string;   // for API field assertion
}

interface AICommitAnalysis {
  summary: string;              // 1-2 sentence analysis of what the code does
  codeChanges: string[];        // bullet list of key changes (max 5)
  impactedAreas: string[];      // feature areas affected
  testCases: AITestCase[];      // specific executable test cases
  riskLevel: 'low' | 'medium' | 'high';
  riskReason: string;
}

async function requestAIAnalysis(
  ticketId: string,
  commitSha: string,
  filesChanged: GitHubFile[],
  ticketTitle?: string,
  ticketDescription?: string
): Promise<AICommitAnalysis | null> {
  try {
    // Prepare diff summary (max 3 files × 1000 chars of patch)
    const diffSummary = filesChanged.slice(0, 5).map(f => ({
      file: f.filename,
      status: f.status,
      additions: f.additions,
      deletions: f.deletions,
      patch: f.patch ? f.patch.slice(0, 1000) : undefined,
    }));

    const qRes = await fetch(`${QA_SHIELD_BASE}/api/ai/queue`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        type: 'analyze-diff',
        payload: {
          identifier: ticketId,
          title: ticketTitle || ticketId,
          description: (ticketDescription || '').slice(0, 500),
          commitSha: commitSha.slice(0, 8),
          files: diffSummary,
          stagingUrl: 'https://dev.creator.fun',
          exampleTokenUrl: 'https://dev.creator.fun/details/Baea4r7r1XW4FUt2k8nToGM3pQtmmidzZP8BcKnQbRHG',
        },
      }),
      signal: AbortSignal.timeout(5000),
    });

    if (!qRes.ok) return null;
    const { taskId } = await qRes.json();
    console.log(`[CommitRunner] AI analysis task ${taskId?.slice(0, 8)} queued for ${ticketId}`);

    // Poll up to 90s for Chief QA to respond
    const start = Date.now();
    while (Date.now() - start < 90_000) {
      await new Promise(r => setTimeout(r, 6000));
      try {
        const poll = await fetch(`${QA_SHIELD_BASE}/api/ai/queue?taskId=${taskId}`, { signal: AbortSignal.timeout(5000) });
        if (poll.ok) {
          const task = await poll.json();
          if (task.status === 'done' && task.result) {
            console.log(`[CommitRunner] Got AI analysis from Chief QA for ${ticketId}`);
            return task.result as AICommitAnalysis;
          }
          if (task.status === 'failed') return null;
        }
      } catch { /* retry */ }
    }
    console.warn(`[CommitRunner] AI analysis timed out for ${ticketId} — using rule-based fallback`);
    return null;
  } catch (err: any) {
    console.warn(`[CommitRunner] AI queue error:`, err.message);
    return null;
  }
}

// ============ Main entry: run full commit analysis ============

export interface CommitRunResult {
  analysis: CommitAnalysis;
  aiAnalysis: AICommitAnalysis | null;
  domResults: Awaited<ReturnType<typeof runDOMChecks>>[];
  apiResults: Awaited<ReturnType<typeof runAPICheck>>[];
  perfResults: Awaited<ReturnType<typeof runPerfCheck>>[];
  secResults: Awaited<ReturnType<typeof runSecurityCheck>>[];
  verdict: 'pass' | 'fail' | 'partial';
  comment: string;
}

export async function runCommitAnalysis(
  commitSha: string,
  commitMessage: string,
  author: string,
  repo: string,
  filesChanged: GitHubFile[],
  ticketId?: string,
  ticketTitle?: string,
  ticketDescription?: string
): Promise<CommitRunResult> {
  // 1. Rule-based analysis (instant — file path → feature mapping)
  const analysis = analyzeCommit(commitSha, commitMessage, author, repo, filesChanged);
  console.log(`[CommitRunner] ${analysis.summary}`);

  // 2. AI analysis (Chief QA generates diff-specific test cases)
  let aiAnalysis: AICommitAnalysis | null = null;
  if (ticketId) {
    aiAnalysis = await requestAIAnalysis(ticketId, commitSha, filesChanged, ticketTitle, ticketDescription);
  }

  // 3. Merge AI test cases with rule-based checks
  //    AI test cases take priority; rule-based fills gaps
  const aiDomPages: Array<{ path: string; checks: any[] }> = [];
  const aiApiChecks: APICheck[] = [];

  if (aiAnalysis?.testCases?.length) {
    // Group AI DOM checks by page
    const domByPage: Record<string, any[]> = {};
    for (const tc of aiAnalysis.testCases) {
      if (tc.type === 'dom' && tc.path && tc.selector) {
        const key = tc.path;
        if (!domByPage[key]) domByPage[key] = [];
        domByPage[key].push({
          description: `[${tc.area}] ${tc.description}`,
          selector: tc.selector,
          action: tc.action || 'exists',
          expectedText: tc.expectedText,
        });
      } else if (tc.type === 'api' && tc.endpoint) {
        aiApiChecks.push({
          endpoint: tc.endpoint.startsWith('http') ? tc.endpoint : `${STAGING_API}${tc.endpoint}`,
          method: 'GET',
          expectedStatus: tc.expectedStatus || 200,
          description: tc.description,
          checks: tc.expectField ? [{ field: tc.expectField, type: 'exists' as const, description: `${tc.description}` }] : [],
        });
      }
    }
    for (const [path, checks] of Object.entries(domByPage)) {
      aiDomPages.push({ path, checks });
    }
    console.log(`[CommitRunner] AI generated ${aiDomPages.length} DOM pages, ${aiApiChecks.length} API checks`);
  }

  // Use AI checks if available, fall back to rule-based
  const domPages = aiDomPages.length > 0 ? aiDomPages : analysis.allPages;
  const apiChecks = aiApiChecks.length > 0 ? aiApiChecks : analysis.allApiChecks;

  // 4. Run all checks
  const [domResults, apiResults, perfResults, secResults] = await Promise.all([
    (async () => {
      const results = [];
      for (const page of domPages) {
        const r = await runDOMChecks(page.path, page.checks);
        results.push(r);
      }
      return results;
    })(),
    Promise.all(apiChecks.map(c => runAPICheck(c))),
    Promise.all(analysis.allPerfEndpoints.slice(0, 2).map(e => runPerfCheck(e))),
    Promise.all(analysis.allSecurityEndpoints.slice(0, 2).map(e => runSecurityCheck(e))),
  ]);

  // 5. Verdict
  const totalFailed = domResults.reduce((s, r) => s + r.failed, 0);
  const totalPassed = domResults.reduce((s, r) => s + r.passed, 0);
  const apiFailed = apiResults.filter(r => !r.ok).length;
  const apiPassed = apiResults.filter(r => r.ok).length;
  const totalChecks = totalPassed + totalFailed + apiPassed + apiFailed;

  let verdict: 'pass' | 'fail' | 'partial';
  if (totalChecks === 0) verdict = 'partial';
  else if (totalFailed === 0 && apiFailed === 0) verdict = 'pass';
  else if (totalPassed === 0 && apiPassed === 0) verdict = 'fail';
  else verdict = 'partial';

  // 6. Build single comprehensive comment
  const comment = buildCommitComment({
    commitSha, commitMessage, author, repo,
    analysis, aiAnalysis,
    domResults, apiResults, perfResults, secResults,
    verdict,
    usedAI: aiAnalysis !== null,
  });

  // 7. Post to Linear (ONE comment only)
  if (ticketId) {
    try {
      const issue = await getIssueByIdentifier(ticketId);
      if (issue) {
        await addComment(issue.id, comment);
        if (verdict === 'pass') {
          await updateIssueState(issue.id, WORKFLOW_STATES.DONE);
          console.log(`[CommitRunner] ${ticketId} → Done ✅`);
        } else if (verdict === 'fail') {
          await updateIssueState(issue.id, WORKFLOW_STATES.TODO);
          console.log(`[CommitRunner] ${ticketId} → Todo ❌`);
        }
      }
    } catch (err: any) {
      console.error(`[CommitRunner] Linear update failed for ${ticketId}:`, err.message);
    }
  }

  return { analysis, aiAnalysis, domResults, apiResults, perfResults, secResults, verdict, comment };
}

// ============ Single comprehensive comment builder ============

function buildCommitComment(opts: {
  commitSha: string;
  commitMessage: string;
  author: string;
  repo: string;
  analysis: CommitAnalysis;
  aiAnalysis: AICommitAnalysis | null;
  domResults: Awaited<ReturnType<typeof runDOMChecks>>[];
  apiResults: Awaited<ReturnType<typeof runAPICheck>>[];
  perfResults: Awaited<ReturnType<typeof runPerfCheck>>[];
  secResults: Awaited<ReturnType<typeof runSecurityCheck>>[];
  verdict: 'pass' | 'fail' | 'partial';
  usedAI: boolean;
}): string {
  const { commitSha, commitMessage, author, repo, analysis, aiAnalysis, domResults, apiResults, perfResults, secResults, verdict, usedAI } = opts;
  const short = commitSha.slice(0, 7);
  const repoName = repo.split('/')[1];
  const commitUrl = `https://github.com/${repo}/commit/${commitSha}`;
  const now = new Date().toISOString();

  const verdictIcon = verdict === 'pass' ? '✅' : verdict === 'fail' ? '❌' : '⚠️';
  const verdictLabel = verdict === 'pass' ? 'PASSED' : verdict === 'fail' ? 'FAILED' : 'PARTIAL';

  const totalPassed = domResults.reduce((s, r) => s + r.passed, 0) + apiResults.filter(r => r.ok).length;
  const totalFailed = domResults.reduce((s, r) => s + r.failed, 0) + apiResults.filter(r => !r.ok).length;
  const totalChecks = totalPassed + totalFailed;

  let out = `## ${verdictIcon} Commit Auto-Analysis — \`${short}\` — ${verdictLabel}

> **Commit:** [\`${short}\`](${commitUrl}) by ${author} on \`${repoName}\`
> **Message:** ${commitMessage.split('\n')[0].slice(0, 100)}

---

`;

  // Code Analysis (AI or rule-based)
  if (aiAnalysis) {
    out += `### 📋 Code Analysis *(AI-generated)*\n`;
    out += `${aiAnalysis.summary}\n\n`;
    if (aiAnalysis.codeChanges?.length) {
      out += `**Key changes:**\n`;
      aiAnalysis.codeChanges.forEach(c => { out += `- ${c}\n`; });
      out += '\n';
    }
    const riskEmoji = aiAnalysis.riskLevel === 'high' ? '🔴' : aiAnalysis.riskLevel === 'medium' ? '🟡' : '🟢';
    out += `**Risk:** ${riskEmoji} ${aiAnalysis.riskLevel.toUpperCase()} — ${aiAnalysis.riskReason}\n\n`;
  } else {
    out += `### 📋 Code Analysis *(rule-based)*\n`;
    out += `${analysis.summary}\n\n`;
    if (analysis.filesChanged?.length) {
      out += `**Changed files:**\n`;
      analysis.filesChanged.slice(0, 5).forEach((f: any) => {
        out += `- \`${f.filename}\` (${f.status}${f.additions ? ` +${f.additions}` : ''}${f.deletions ? `/-${f.deletions}` : ''})\n`;
      });
      out += '\n';
    }
  }

  // Impacted Areas
  const areas = aiAnalysis?.impactedAreas?.length ? aiAnalysis.impactedAreas : analysis.impactAreas.map(a => a.feature);
  if (areas.length) {
    out += `### 🎯 Impacted Areas\n`;
    areas.forEach((a, i) => { out += `${i + 1}. ${a}\n`; });
    out += '\n';
  }

  // Test Cases + Results
  out += `### 🧪 Test Cases Executed\n`;
  out += `*(${usedAI ? 'AI-generated test cases' : 'Rule-based test cases'} — ${totalChecks} total)*\n\n`;

  if (totalChecks === 0) {
    out += `> ⚠️ No executable test cases were generated for this commit.\n`;
    out += `> ${usedAI ? 'AI analysis did not produce DOM/API checks.' : 'Rule-based mapper found no matching patterns.'}\n`;
    out += `> Manual verification required.\n\n`;
  } else {
    // DOM results
    let checkNum = 1;
    for (const page of domResults) {
      out += `**Page: \`${page.path}\`**\n`;
      for (const c of page.checks) {
        const icon = c.passed ? '✅' : '❌';
        out += `${checkNum}. ${icon} ${c.description}\n`;
        if (!c.passed && c.error) out += `   > ⚠️ ${c.error}\n`;
        checkNum++;
      }
      out += '\n';
    }

    // API results
    if (apiResults.length > 0) {
      out += `**API Checks**\n`;
      for (const r of apiResults) {
        const icon = r.ok ? '✅' : '❌';
        const ep = r.endpoint.replace('https://dev.bep.creator.fun', '');
        out += `${checkNum}. ${icon} \`GET ${ep}\` → HTTP ${r.status || '?'}\n`;
        if (r.issues?.length) r.issues.forEach(i => { out += `   > ⚠️ ${i}\n`; });
        checkNum++;
      }
      out += '\n';
    }
  }

  // Summary table
  out += `### 📊 Results Summary\n`;
  out += `| Total | ✅ Passed | ❌ Failed |\n`;
  out += `|-------|-----------|----------|\n`;
  out += `| ${totalChecks} | ${totalPassed} | ${totalFailed} |\n\n`;

  // Perf results (only if relevant)
  const perfIssues = perfResults.filter(p => (p.deltaPct ?? 0) > 50);
  if (perfIssues.length > 0) {
    out += `### ⚡ Performance Flags\n`;
    perfIssues.forEach(p => {
      out += `- \`${p.endpoint.replace('https://dev.bep.creator.fun', '')}\` ${p.ourMs}ms vs ${p.fastestCompMs}ms (${p.fastestCompName}) — ${p.deltaPct}% slower\n`;
    });
    out += '\n';
  }

  // Security flags (only if found)
  const secIssues = secResults.flatMap(s => s.issues.map(i => `\`${s.endpoint.replace('https://dev.bep.creator.fun', '')}\`: ${i}`));
  if (secIssues.length > 0) {
    out += `### 🔒 Security Flags\n`;
    secIssues.forEach(i => { out += `- ${i}\n`; });
    out += '\n';
  }

  out += `---\n*QA Shield 🛡️ auto-analysis — ${now}*`;
  return out;
}
