/**
 * POST /api/security/scan
 * Scans endpoints for security vulnerabilities
 */

import { NextRequest, NextResponse } from 'next/server';
import { scanEndpoint, comparativeBehnchmark } from '@/lib/scanner';
import { getIssueByIdentifier, addComment } from '@/lib/linear';

const DEFAULT_ENDPOINTS = [
  '/api/token',
  '/api/watchlist',
  '/api/user',
  '/api/chat',
  '/api/trade',
  '/api/holdings',
  '/api/leaderboard',
  '/api/rewards',
  '/api/fees',
];

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { endpoints, baseUrl, identifier, postComment = false } = body;

    const apiBase = baseUrl || process.env.STAGING_API_URL || 'https://dev.bep.creator.fun';
    const endpointsToScan = endpoints || DEFAULT_ENDPOINTS;

    const results = await Promise.all(
      endpointsToScan.map((ep: string) => scanEndpoint(`${apiBase}${ep}`))
    );

    const summary = {
      total: results.length,
      passed: results.filter(r => r.overallStatus === 'pass').length,
      warnings: results.filter(r => r.overallStatus === 'warn').length,
      failed: results.filter(r => r.overallStatus === 'fail').length,
    };

    // Post to Linear if requested
    if (postComment && identifier) {
      try {
        const issue = await getIssueByIdentifier(identifier);
        let comment = `## 🛡️ QA Shield — Security Scan Report\n\n`;
        comment += `**Scanned at:** ${new Date().toISOString()}\n\n`;
        comment += `| Status | Count |\n|--------|-------|\n`;
        comment += `| ✅ Passed | ${summary.passed} |\n`;
        comment += `| ⚠️ Warnings | ${summary.warnings} |\n`;
        comment += `| ❌ Failed | ${summary.failed} |\n\n`;

        for (const r of results) {
          const icon = r.overallStatus === 'pass' ? '✅' : r.overallStatus === 'fail' ? '❌' : '⚠️';
          const ep = r.endpoint.split('/api')[1] || r.endpoint;
          comment += `${icon} **\`/api${ep}\`**\n`;
          for (const c of r.checks) {
            if (c.status !== 'pass') {
              comment += `- [${c.severity.toUpperCase()}] [${c.type.toUpperCase()}] ${c.details}\n`;
            }
          }
          comment += '\n';
        }

        comment += `---\n_Generated by QA Shield 🛡️ — automated security scan_`;
        await addComment(issue.id, comment);
      } catch (e) {
        console.error('Failed to post security scan to Linear:', e);
      }
    }

    return NextResponse.json({
      success: true,
      summary,
      results,
      scannedAt: new Date().toISOString(),
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

// GET: Quick scan of default endpoints
export async function GET() {
  const apiBase = process.env.STAGING_API_URL || 'https://dev.bep.creator.fun';

  const results = await Promise.all(
    DEFAULT_ENDPOINTS.slice(0, 5).map(ep => scanEndpoint(`${apiBase}${ep}`))
  );

  return NextResponse.json({
    success: true,
    results,
    scannedAt: new Date().toISOString(),
  });
}
